//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Bar : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Bar(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Bar obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Bar() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SwigFooBarPINVOKE.delete_Bar(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public IBar impl {
    set {
      SwigFooBarPINVOKE.Bar_impl_set(swigCPtr, IBar.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SwigFooBarPINVOKE.Bar_impl_get(swigCPtr);
      IBar ret = (cPtr == global::System.IntPtr.Zero) ? null : new IBar(cPtr, false);
      return ret;
    } 
  }

  public Bar() : this(SwigFooBarPINVOKE.new_Bar(), true) {
  }

  public void Register(IBar impl) {
    SwigFooBarPINVOKE.Bar_Register(swigCPtr, IBar.getCPtr(impl));
  }

  public int PerformGetNumber() {
    int ret = SwigFooBarPINVOKE.Bar_PerformGetNumber(swigCPtr);
    return ret;
  }

}
