// Generated by SharpCpp

#include "Bar.hpp"

using namespace CSharpFooBarLibrary;

Bar::Bar() {
}

void Bar::Register(std::shared_ptr<IBar> ibar) {
  this->impl = ibar;
}

int32_t Bar::PerformGetNumber() {
  if (impl == nullptr) {
    return -1;
  } else {
    return impl->GetNumber();
  }
}
