// Generated by SharpCpp

#pragma once

#include <memory>
#include "IBar.hpp"
#include <cstdint>

namespace CSharpFooBarLibrary {
  class Bar {
    private:
      std::shared_ptr<IBar> impl;

    public:
      void Register(std::shared_ptr<IBar> ibar);
      int32_t PerformGetNumber();

      Bar();
  };
} // namespace CSharpFooBarLibrary
