// Generated by SharpCpp

#pragma once

#include <cstdint>

namespace CSharpFooBarLibrary {
  class IBar {
  public:
    virtual int32_t GetNumber() = 0;

    virtual ~IBar();
    IBar();
  };
} // namespace CSharpFooBarLibrary
